/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_windowGestionEtudiant (void);
GtkWidget* create_windowModifierEtudiant (void);
GtkWidget* create_windowSupprimerEtudiant (void);
GtkWidget* create_windowListeEtudiants (void);
GtkWidget* create_dialog1 (void);
GtkWidget* create_dialog2 (void);
GtkWidget* create_dialog3 (void);
GtkWidget* create_windowChamps (void);
GtkWidget* create_dialog5 (void);
GtkWidget* create_dialog6 (void);
GtkWidget* create_windowAjoutEtudiant (void);
GtkWidget* create_ModifierEtudiant (void);
GtkWidget* create_windowcalcul (void);
GtkWidget* create_Aceuill (void);
GtkWidget* create_gestion1 (void);
GtkWidget* create_Cap_def (void);
GtkWidget* create_Ges_alrm (void);
GtkWidget* create_inscription (void);
GtkWidget* create_windowAuthentification (void);
GtkWidget* create_windowAdmin (void);
GtkWidget* create_etage_panne (void);
GtkWidget* create_Modificationpersonne (void);
GtkWidget* create_AjoutPersonne (void);
GtkWidget* create_liste_des_utilisateurs (void);
GtkWidget* create_Suppressionper (void);
GtkWidget* create_dashboard (void);
GtkWidget* create_mod (void);
GtkWidget* create_af (void);
GtkWidget* create_aj (void);
GtkWidget* create_ajouter (void);
GtkWidget* create_admin (void);
GtkWidget* create_modif (void);
GtkWidget* create_alerte (void);
GtkWidget* create_Gestionf_fn (void);
GtkWidget* create_Rechercher_fn (void);
GtkWidget* create_Supprimer_fn (void);
GtkWidget* create_Ajout_fn (void);
GtkWidget* create_Modifier_fn (void);
