/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_Gestionf_fn (void)
{
  GtkWidget *Gestionf_fn;
  GtkWidget *fixed2;
  GtkWidget *treeview_fn;
  GtkWidget *label37;
  GtkWidget *label_affichage_meilleur_menu;
  GtkWidget *button_meilleur_fn;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label8;
  GtkWidget *button_rafraichir_fn;
  GtkWidget *alignment17;
  GtkWidget *hbox17;
  GtkWidget *image28;
  GtkWidget *label43;
  GtkWidget *button_supprimer_fn;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label7;
  GtkWidget *button_modifier_fn;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label6;
  GtkWidget *button_ajouter_fn;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label5;

  Gestionf_fn = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (Gestionf_fn, 769, 550);
  gtk_window_set_title (GTK_WINDOW (Gestionf_fn), _("Gestion"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (Gestionf_fn), fixed2);

  treeview_fn = gtk_tree_view_new ();
  gtk_widget_show (treeview_fn);
  gtk_fixed_put (GTK_FIXED (fixed2), treeview_fn, 24, 232);
  gtk_widget_set_size_request (treeview_fn, 708, 240);

  label37 = gtk_label_new (_("---------------- Espace Nutritionniste ----------------\n"));
  gtk_widget_show (label37);
  gtk_fixed_put (GTK_FIXED (fixed2), label37, 208, 24);
  gtk_widget_set_size_request (label37, 368, 56);

  label_affichage_meilleur_menu = gtk_label_new (_("Le meilleur menu est = "));
  gtk_widget_show (label_affichage_meilleur_menu);
  gtk_fixed_put (GTK_FIXED (fixed2), label_affichage_meilleur_menu, 24, 176);
  gtk_widget_set_size_request (label_affichage_meilleur_menu, 752, 24);

  button_meilleur_fn = gtk_button_new ();
  gtk_widget_show (button_meilleur_fn);
  gtk_fixed_put (GTK_FIXED (fixed2), button_meilleur_fn, 592, 112);
  gtk_widget_set_size_request (button_meilleur_fn, 130, 30);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (button_meilleur_fn), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-goto-top", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label8 = gtk_label_new_with_mnemonic (_("Meilleur menu"));
  gtk_widget_show (label8);
  gtk_box_pack_start (GTK_BOX (hbox6), label8, FALSE, FALSE, 0);

  button_rafraichir_fn = gtk_button_new ();
  gtk_widget_show (button_rafraichir_fn);
  gtk_fixed_put (GTK_FIXED (fixed2), button_rafraichir_fn, 448, 112);
  gtk_widget_set_size_request (button_rafraichir_fn, 130, 30);

  alignment17 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment17);
  gtk_container_add (GTK_CONTAINER (button_rafraichir_fn), alignment17);

  hbox17 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox17);
  gtk_container_add (GTK_CONTAINER (alignment17), hbox17);

  image28 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image28);
  gtk_box_pack_start (GTK_BOX (hbox17), image28, FALSE, FALSE, 0);

  label43 = gtk_label_new_with_mnemonic (_("  Rafraichir"));
  gtk_widget_show (label43);
  gtk_box_pack_start (GTK_BOX (hbox17), label43, FALSE, FALSE, 0);

  button_supprimer_fn = gtk_button_new ();
  gtk_widget_show (button_supprimer_fn);
  gtk_fixed_put (GTK_FIXED (fixed2), button_supprimer_fn, 304, 112);
  gtk_widget_set_size_request (button_supprimer_fn, 130, 30);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (button_supprimer_fn), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-cut", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label7 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label7);
  gtk_box_pack_start (GTK_BOX (hbox5), label7, FALSE, FALSE, 0);

  button_modifier_fn = gtk_button_new ();
  gtk_widget_show (button_modifier_fn);
  gtk_fixed_put (GTK_FIXED (fixed2), button_modifier_fn, 160, 112);
  gtk_widget_set_size_request (button_modifier_fn, 130, 30);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (button_modifier_fn), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label6 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label6);
  gtk_box_pack_start (GTK_BOX (hbox4), label6, FALSE, FALSE, 0);

  button_ajouter_fn = gtk_button_new ();
  gtk_widget_show (button_ajouter_fn);
  gtk_fixed_put (GTK_FIXED (fixed2), button_ajouter_fn, 16, 112);
  gtk_widget_set_size_request (button_ajouter_fn, 130, 30);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (button_ajouter_fn), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label5 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label5);
  gtk_box_pack_start (GTK_BOX (hbox3), label5, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) treeview_fn, "row_activated",
                    G_CALLBACK (on_treeview_fn_row_activated),
                    NULL);
  g_signal_connect ((gpointer) button_meilleur_fn, "clicked",
                    G_CALLBACK (on_button_meilleur_fn_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_rafraichir_fn, "clicked",
                    G_CALLBACK (on_button_rafraichir_fn_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_supprimer_fn, "clicked",
                    G_CALLBACK (on_button_supprimer_fn_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_modifier_fn, "clicked",
                    G_CALLBACK (on_button_modifier_fn_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_ajouter_fn, "clicked",
                    G_CALLBACK (on_button_ajouter_fn_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Gestionf_fn, Gestionf_fn, "Gestionf_fn");
  GLADE_HOOKUP_OBJECT (Gestionf_fn, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (Gestionf_fn, treeview_fn, "treeview_fn");
  GLADE_HOOKUP_OBJECT (Gestionf_fn, label37, "label37");
  GLADE_HOOKUP_OBJECT (Gestionf_fn, label_affichage_meilleur_menu, "label_affichage_meilleur_menu");
  GLADE_HOOKUP_OBJECT (Gestionf_fn, button_meilleur_fn, "button_meilleur_fn");
  GLADE_HOOKUP_OBJECT (Gestionf_fn, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (Gestionf_fn, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (Gestionf_fn, image6, "image6");
  GLADE_HOOKUP_OBJECT (Gestionf_fn, label8, "label8");
  GLADE_HOOKUP_OBJECT (Gestionf_fn, button_rafraichir_fn, "button_rafraichir_fn");
  GLADE_HOOKUP_OBJECT (Gestionf_fn, alignment17, "alignment17");
  GLADE_HOOKUP_OBJECT (Gestionf_fn, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (Gestionf_fn, image28, "image28");
  GLADE_HOOKUP_OBJECT (Gestionf_fn, label43, "label43");
  GLADE_HOOKUP_OBJECT (Gestionf_fn, button_supprimer_fn, "button_supprimer_fn");
  GLADE_HOOKUP_OBJECT (Gestionf_fn, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (Gestionf_fn, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (Gestionf_fn, image5, "image5");
  GLADE_HOOKUP_OBJECT (Gestionf_fn, label7, "label7");
  GLADE_HOOKUP_OBJECT (Gestionf_fn, button_modifier_fn, "button_modifier_fn");
  GLADE_HOOKUP_OBJECT (Gestionf_fn, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (Gestionf_fn, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (Gestionf_fn, image4, "image4");
  GLADE_HOOKUP_OBJECT (Gestionf_fn, label6, "label6");
  GLADE_HOOKUP_OBJECT (Gestionf_fn, button_ajouter_fn, "button_ajouter_fn");
  GLADE_HOOKUP_OBJECT (Gestionf_fn, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (Gestionf_fn, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (Gestionf_fn, image3, "image3");
  GLADE_HOOKUP_OBJECT (Gestionf_fn, label5, "label5");

  return Gestionf_fn;
}

GtkWidget*
create_Rechercher_fn (void)
{
  GtkWidget *Rechercher_fn;
  GtkWidget *fixed3;
  GtkWidget *label_rechercher;
  GtkWidget *label_jour_rechercher;
  GtkWidget *label_temps_rechercher;
  GtkWidget *checkbutton_dejeuner_rechercher_fn;
  GtkWidget *checkbutton_diner_rechercher_fn;
  GtkWidget *combobox_jour_rechercher_fn;
  GtkWidget *button_chercher_fn;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *image25;
  GtkWidget *label38;
  GtkWidget *button_home5_fn;
  GtkWidget *image9;

  Rechercher_fn = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (Rechercher_fn, 555, 400);
  gtk_window_set_title (GTK_WINDOW (Rechercher_fn), _("Rechercher"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (Rechercher_fn), fixed3);

  label_rechercher = gtk_label_new (_("------ Espace Nutritionniste ------\n          ------ Recherche------"));
  gtk_widget_show (label_rechercher);
  gtk_fixed_put (GTK_FIXED (fixed3), label_rechercher, 152, 16);
  gtk_widget_set_size_request (label_rechercher, 232, 64);

  label_jour_rechercher = gtk_label_new (_("Jour De La Semaine :"));
  gtk_widget_show (label_jour_rechercher);
  gtk_fixed_put (GTK_FIXED (fixed3), label_jour_rechercher, 40, 192);
  gtk_widget_set_size_request (label_jour_rechercher, 184, 40);

  label_temps_rechercher = gtk_label_new (_("Temps  :"));
  gtk_widget_show (label_temps_rechercher);
  gtk_fixed_put (GTK_FIXED (fixed3), label_temps_rechercher, 96, 112);
  gtk_widget_set_size_request (label_temps_rechercher, 72, 32);

  checkbutton_dejeuner_rechercher_fn = gtk_check_button_new_with_mnemonic (_("D\303\251jeuner"));
  gtk_widget_show (checkbutton_dejeuner_rechercher_fn);
  gtk_fixed_put (GTK_FIXED (fixed3), checkbutton_dejeuner_rechercher_fn, 280, 96);
  gtk_widget_set_size_request (checkbutton_dejeuner_rechercher_fn, 120, 32);

  checkbutton_diner_rechercher_fn = gtk_check_button_new_with_mnemonic (_("Diner"));
  gtk_widget_show (checkbutton_diner_rechercher_fn);
  gtk_fixed_put (GTK_FIXED (fixed3), checkbutton_diner_rechercher_fn, 280, 136);
  gtk_widget_set_size_request (checkbutton_diner_rechercher_fn, 118, 32);

  combobox_jour_rechercher_fn = gtk_combo_box_new_text ();
  gtk_widget_show (combobox_jour_rechercher_fn);
  gtk_fixed_put (GTK_FIXED (fixed3), combobox_jour_rechercher_fn, 245, 200);
  gtk_widget_set_size_request (combobox_jour_rechercher_fn, 131, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_jour_rechercher_fn), _("lundi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_jour_rechercher_fn), _("mardi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_jour_rechercher_fn), _("mercredi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_jour_rechercher_fn), _("jeudi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_jour_rechercher_fn), _("vendredi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_jour_rechercher_fn), _("samedi"));

  button_chercher_fn = gtk_button_new ();
  gtk_widget_show (button_chercher_fn);
  gtk_fixed_put (GTK_FIXED (fixed3), button_chercher_fn, 200, 288);
  gtk_widget_set_size_request (button_chercher_fn, 136, 56);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (button_chercher_fn), alignment15);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  image25 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image25);
  gtk_box_pack_start (GTK_BOX (hbox15), image25, FALSE, FALSE, 0);

  label38 = gtk_label_new_with_mnemonic (_(" chercher"));
  gtk_widget_show (label38);
  gtk_box_pack_start (GTK_BOX (hbox15), label38, FALSE, FALSE, 0);

  button_home5_fn = gtk_button_new ();
  gtk_widget_show (button_home5_fn);
  gtk_fixed_put (GTK_FIXED (fixed3), button_home5_fn, 16, 16);
  gtk_widget_set_size_request (button_home5_fn, 40, 32);

  image9 = gtk_image_new_from_stock ("gtk-home", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_container_add (GTK_CONTAINER (button_home5_fn), image9);

  g_signal_connect ((gpointer) checkbutton_dejeuner_rechercher_fn, "toggled",
                    G_CALLBACK (on_checkbutton_dejeuner_rechercher_fn_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton_diner_rechercher_fn, "toggled",
                    G_CALLBACK (on_checkbutton_diner_rechercher_fn_toggled),
                    NULL);
  g_signal_connect ((gpointer) button_chercher_fn, "clicked",
                    G_CALLBACK (on_button_chercher_fn_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_home5_fn, "clicked",
                    G_CALLBACK (on_button_home5_fn_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Rechercher_fn, Rechercher_fn, "Rechercher_fn");
  GLADE_HOOKUP_OBJECT (Rechercher_fn, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (Rechercher_fn, label_rechercher, "label_rechercher");
  GLADE_HOOKUP_OBJECT (Rechercher_fn, label_jour_rechercher, "label_jour_rechercher");
  GLADE_HOOKUP_OBJECT (Rechercher_fn, label_temps_rechercher, "label_temps_rechercher");
  GLADE_HOOKUP_OBJECT (Rechercher_fn, checkbutton_dejeuner_rechercher_fn, "checkbutton_dejeuner_rechercher_fn");
  GLADE_HOOKUP_OBJECT (Rechercher_fn, checkbutton_diner_rechercher_fn, "checkbutton_diner_rechercher_fn");
  GLADE_HOOKUP_OBJECT (Rechercher_fn, combobox_jour_rechercher_fn, "combobox_jour_rechercher_fn");
  GLADE_HOOKUP_OBJECT (Rechercher_fn, button_chercher_fn, "button_chercher_fn");
  GLADE_HOOKUP_OBJECT (Rechercher_fn, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (Rechercher_fn, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (Rechercher_fn, image25, "image25");
  GLADE_HOOKUP_OBJECT (Rechercher_fn, label38, "label38");
  GLADE_HOOKUP_OBJECT (Rechercher_fn, button_home5_fn, "button_home5_fn");
  GLADE_HOOKUP_OBJECT (Rechercher_fn, image9, "image9");

  return Rechercher_fn;
}

GtkWidget*
create_Ajout_fn (void)
{
  GtkWidget *Ajout_fn;
  GtkWidget *fixed4;
  GtkWidget *label_ajouter_fn;
  GtkWidget *label_temps_ajouter_fn;
  GtkWidget *table1;
  GtkWidget *label_jour1;
  GtkWidget *label_entree1;
  GtkWidget *label_plat_principal_1;
  GtkWidget *label_dessert1;
  GtkWidget *entry_entree_ajouter_fn;
  GtkWidget *entry_plat_principal_ajouter_fn;
  GtkWidget *entry_dessert_ajouter_fn;
  GtkWidget *label_dechets1;
  GtkObject *spinbutton_dechets_ajouter_fn_adj;
  GtkWidget *spinbutton_dechets_ajouter_fn;
  GtkWidget *combobox_jour_ajouter_fn;
  GtkWidget *button_enregister_fn;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image14;
  GtkWidget *label15;
  GtkWidget *checkbutton_diner_ajouter_fn;
  GtkWidget *checkbutton_dejeuner_ajouter_fn;
  GtkWidget *button_home1_fn;
  GtkWidget *image12;

  Ajout_fn = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (Ajout_fn, 600, 648);
  gtk_window_set_title (GTK_WINDOW (Ajout_fn), _("Ajout"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (Ajout_fn), fixed4);

  label_ajouter_fn = gtk_label_new (_("Espace Nutritionniste\n         ----- Ajouter -----"));
  gtk_widget_show (label_ajouter_fn);
  gtk_fixed_put (GTK_FIXED (fixed4), label_ajouter_fn, 184, 8);
  gtk_widget_set_size_request (label_ajouter_fn, 240, 64);

  label_temps_ajouter_fn = gtk_label_new (_("Temps  :"));
  gtk_widget_show (label_temps_ajouter_fn);
  gtk_fixed_put (GTK_FIXED (fixed4), label_temps_ajouter_fn, 120, 120);
  gtk_widget_set_size_request (label_temps_ajouter_fn, 72, 32);

  table1 = gtk_table_new (5, 2, FALSE);
  gtk_widget_show (table1);
  gtk_fixed_put (GTK_FIXED (fixed4), table1, 80, 208);
  gtk_widget_set_size_request (table1, 426, 320);
  gtk_table_set_row_spacings (GTK_TABLE (table1), 18);
  gtk_table_set_col_spacings (GTK_TABLE (table1), 8);

  label_jour1 = gtk_label_new (_("Jour De La Semaine :"));
  gtk_widget_show (label_jour1);
  gtk_table_attach (GTK_TABLE (table1), label_jour1, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (label_jour1, 184, 40);

  label_entree1 = gtk_label_new (_("Entree"));
  gtk_widget_show (label_entree1);
  gtk_table_attach (GTK_TABLE (table1), label_entree1, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (label_entree1, 184, 40);

  label_plat_principal_1 = gtk_label_new (_("Plat principal"));
  gtk_widget_show (label_plat_principal_1);
  gtk_table_attach (GTK_TABLE (table1), label_plat_principal_1, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (label_plat_principal_1, 184, 40);

  label_dessert1 = gtk_label_new (_("Dessert"));
  gtk_widget_show (label_dessert1);
  gtk_table_attach (GTK_TABLE (table1), label_dessert1, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (label_dessert1, 184, 40);

  entry_entree_ajouter_fn = gtk_entry_new ();
  gtk_widget_show (entry_entree_ajouter_fn);
  gtk_table_attach (GTK_TABLE (table1), entry_entree_ajouter_fn, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_entree_ajouter_fn), 8226);

  entry_plat_principal_ajouter_fn = gtk_entry_new ();
  gtk_widget_show (entry_plat_principal_ajouter_fn);
  gtk_table_attach (GTK_TABLE (table1), entry_plat_principal_ajouter_fn, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_plat_principal_ajouter_fn), 8226);

  entry_dessert_ajouter_fn = gtk_entry_new ();
  gtk_widget_show (entry_dessert_ajouter_fn);
  gtk_table_attach (GTK_TABLE (table1), entry_dessert_ajouter_fn, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_dessert_ajouter_fn), 8226);

  label_dechets1 = gtk_label_new (_("D\303\251chets en kg :"));
  gtk_widget_show (label_dechets1);
  gtk_table_attach (GTK_TABLE (table1), label_dechets1, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (label_dechets1, 144, 40);

  spinbutton_dechets_ajouter_fn_adj = gtk_adjustment_new (0, 0, 100, 1, 10, 10);
  spinbutton_dechets_ajouter_fn = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_dechets_ajouter_fn_adj), 1, 0);
  gtk_widget_show (spinbutton_dechets_ajouter_fn);
  gtk_table_attach (GTK_TABLE (table1), spinbutton_dechets_ajouter_fn, 1, 2, 4, 5,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (spinbutton_dechets_ajouter_fn, 60, 27);

  combobox_jour_ajouter_fn = gtk_combo_box_new_text ();
  gtk_widget_show (combobox_jour_ajouter_fn);
  gtk_table_attach (GTK_TABLE (table1), combobox_jour_ajouter_fn, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_jour_ajouter_fn), _("lundi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_jour_ajouter_fn), _("mardi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_jour_ajouter_fn), _("mercredi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_jour_ajouter_fn), _("jeudi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_jour_ajouter_fn), _("vendredi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_jour_ajouter_fn), _("samedi"));

  button_enregister_fn = gtk_button_new ();
  gtk_widget_show (button_enregister_fn);
  gtk_fixed_put (GTK_FIXED (fixed4), button_enregister_fn, 224, 552);
  gtk_widget_set_size_request (button_enregister_fn, 136, 48);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (button_enregister_fn), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image14 = gtk_image_new_from_stock ("gtk-save", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox8), image14, FALSE, FALSE, 0);

  label15 = gtk_label_new_with_mnemonic (_(" Enregister"));
  gtk_widget_show (label15);
  gtk_box_pack_start (GTK_BOX (hbox8), label15, FALSE, FALSE, 0);

  checkbutton_diner_ajouter_fn = gtk_check_button_new_with_mnemonic (_("Diner"));
  gtk_widget_show (checkbutton_diner_ajouter_fn);
  gtk_fixed_put (GTK_FIXED (fixed4), checkbutton_diner_ajouter_fn, 272, 144);
  gtk_widget_set_size_request (checkbutton_diner_ajouter_fn, 118, 32);

  checkbutton_dejeuner_ajouter_fn = gtk_check_button_new_with_mnemonic (_("D\303\251jeuner"));
  gtk_widget_show (checkbutton_dejeuner_ajouter_fn);
  gtk_fixed_put (GTK_FIXED (fixed4), checkbutton_dejeuner_ajouter_fn, 272, 112);
  gtk_widget_set_size_request (checkbutton_dejeuner_ajouter_fn, 120, 32);

  button_home1_fn = gtk_button_new ();
  gtk_widget_show (button_home1_fn);
  gtk_fixed_put (GTK_FIXED (fixed4), button_home1_fn, 32, 24);
  gtk_widget_set_size_request (button_home1_fn, 48, 32);

  image12 = gtk_image_new_from_stock ("gtk-home", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_container_add (GTK_CONTAINER (button_home1_fn), image12);

  g_signal_connect ((gpointer) button_enregister_fn, "clicked",
                    G_CALLBACK (on_button_enregister_fn_clicked),
                    NULL);
  g_signal_connect ((gpointer) checkbutton_diner_ajouter_fn, "toggled",
                    G_CALLBACK (on_checkbutton_diner_ajouter_fn_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton_dejeuner_ajouter_fn, "toggled",
                    G_CALLBACK (on_checkbutton_dejeuner_ajouter_fn_toggled),
                    NULL);
  g_signal_connect ((gpointer) button_home1_fn, "clicked",
                    G_CALLBACK (on_button_home1_fn_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Ajout_fn, Ajout_fn, "Ajout_fn");
  GLADE_HOOKUP_OBJECT (Ajout_fn, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (Ajout_fn, label_ajouter_fn, "label_ajouter_fn");
  GLADE_HOOKUP_OBJECT (Ajout_fn, label_temps_ajouter_fn, "label_temps_ajouter_fn");
  GLADE_HOOKUP_OBJECT (Ajout_fn, table1, "table1");
  GLADE_HOOKUP_OBJECT (Ajout_fn, label_jour1, "label_jour1");
  GLADE_HOOKUP_OBJECT (Ajout_fn, label_entree1, "label_entree1");
  GLADE_HOOKUP_OBJECT (Ajout_fn, label_plat_principal_1, "label_plat_principal_1");
  GLADE_HOOKUP_OBJECT (Ajout_fn, label_dessert1, "label_dessert1");
  GLADE_HOOKUP_OBJECT (Ajout_fn, entry_entree_ajouter_fn, "entry_entree_ajouter_fn");
  GLADE_HOOKUP_OBJECT (Ajout_fn, entry_plat_principal_ajouter_fn, "entry_plat_principal_ajouter_fn");
  GLADE_HOOKUP_OBJECT (Ajout_fn, entry_dessert_ajouter_fn, "entry_dessert_ajouter_fn");
  GLADE_HOOKUP_OBJECT (Ajout_fn, label_dechets1, "label_dechets1");
  GLADE_HOOKUP_OBJECT (Ajout_fn, spinbutton_dechets_ajouter_fn, "spinbutton_dechets_ajouter_fn");
  GLADE_HOOKUP_OBJECT (Ajout_fn, combobox_jour_ajouter_fn, "combobox_jour_ajouter_fn");
  GLADE_HOOKUP_OBJECT (Ajout_fn, button_enregister_fn, "button_enregister_fn");
  GLADE_HOOKUP_OBJECT (Ajout_fn, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (Ajout_fn, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (Ajout_fn, image14, "image14");
  GLADE_HOOKUP_OBJECT (Ajout_fn, label15, "label15");
  GLADE_HOOKUP_OBJECT (Ajout_fn, checkbutton_diner_ajouter_fn, "checkbutton_diner_ajouter_fn");
  GLADE_HOOKUP_OBJECT (Ajout_fn, checkbutton_dejeuner_ajouter_fn, "checkbutton_dejeuner_ajouter_fn");
  GLADE_HOOKUP_OBJECT (Ajout_fn, button_home1_fn, "button_home1_fn");
  GLADE_HOOKUP_OBJECT (Ajout_fn, image12, "image12");

  return Ajout_fn;
}

GtkWidget*
create_Supprimer_fn (void)
{
  GtkWidget *Supprimer_fn;
  GtkWidget *fixed5;
  GtkWidget *label_temps3_fn;
  GtkWidget *label_jour3_fn;
  GtkWidget *label_suppresssion_fn;
  GtkWidget *combobox_suppression_fn;
  GtkWidget *radiobutton_diner3_fn;
  GSList *radiobutton_diner3_fn_group = NULL;
  GtkWidget *radiobutton_dejeuner3_fn;
  GtkWidget *button_home3_fn;
  GtkWidget *image17;
  GtkWidget *button_suppression_fn;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image15;
  GtkWidget *label19;

  Supprimer_fn = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (Supprimer_fn, 555, 400);
  gtk_window_set_title (GTK_WINDOW (Supprimer_fn), _("Supprimer"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (Supprimer_fn), fixed5);

  label_temps3_fn = gtk_label_new (_("Temps:"));
  gtk_widget_show (label_temps3_fn);
  gtk_fixed_put (GTK_FIXED (fixed5), label_temps3_fn, 80, 144);
  gtk_widget_set_size_request (label_temps3_fn, 73, 32);

  label_jour3_fn = gtk_label_new (_("Jour De la Semaine :"));
  gtk_widget_show (label_jour3_fn);
  gtk_fixed_put (GTK_FIXED (fixed5), label_jour3_fn, 72, 200);
  gtk_widget_set_size_request (label_jour3_fn, 152, 48);

  label_suppresssion_fn = gtk_label_new (_("   Espace Nutritionniste\n      ---- Suppresssion ----"));
  gtk_widget_show (label_suppresssion_fn);
  gtk_fixed_put (GTK_FIXED (fixed5), label_suppresssion_fn, 176, 32);
  gtk_widget_set_size_request (label_suppresssion_fn, 184, 56);

  combobox_suppression_fn = gtk_combo_box_new_text ();
  gtk_widget_show (combobox_suppression_fn);
  gtk_fixed_put (GTK_FIXED (fixed5), combobox_suppression_fn, 264, 208);
  gtk_widget_set_size_request (combobox_suppression_fn, 169, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_suppression_fn), _("lundi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_suppression_fn), _("mardi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_suppression_fn), _("mercredi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_suppression_fn), _("jeudi "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_suppression_fn), _("vendredi "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_suppression_fn), _("samedi"));

  radiobutton_diner3_fn = gtk_radio_button_new_with_mnemonic (NULL, _("Diner"));
  gtk_widget_show (radiobutton_diner3_fn);
  gtk_fixed_put (GTK_FIXED (fixed5), radiobutton_diner3_fn, 320, 144);
  gtk_widget_set_size_request (radiobutton_diner3_fn, 120, 32);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_diner3_fn), radiobutton_diner3_fn_group);
  radiobutton_diner3_fn_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_diner3_fn));

  radiobutton_dejeuner3_fn = gtk_radio_button_new_with_mnemonic (NULL, _("D\303\251jeuner"));
  gtk_widget_show (radiobutton_dejeuner3_fn);
  gtk_fixed_put (GTK_FIXED (fixed5), radiobutton_dejeuner3_fn, 192, 144);
  gtk_widget_set_size_request (radiobutton_dejeuner3_fn, 128, 32);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_dejeuner3_fn), radiobutton_diner3_fn_group);
  radiobutton_diner3_fn_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_dejeuner3_fn));

  button_home3_fn = gtk_button_new ();
  gtk_widget_show (button_home3_fn);
  gtk_fixed_put (GTK_FIXED (fixed5), button_home3_fn, 8, 8);
  gtk_widget_set_size_request (button_home3_fn, 40, 32);

  image17 = gtk_image_new_from_stock ("gtk-home", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image17);
  gtk_container_add (GTK_CONTAINER (button_home3_fn), image17);

  button_suppression_fn = gtk_button_new ();
  gtk_widget_show (button_suppression_fn);
  gtk_fixed_put (GTK_FIXED (fixed5), button_suppression_fn, 200, 312);
  gtk_widget_set_size_request (button_suppression_fn, 128, 40);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (button_suppression_fn), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image15 = gtk_image_new_from_stock ("gtk-close", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox9), image15, FALSE, FALSE, 0);

  label19 = gtk_label_new_with_mnemonic (_(" supprimer"));
  gtk_widget_show (label19);
  gtk_box_pack_start (GTK_BOX (hbox9), label19, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) radiobutton_diner3_fn, "toggled",
                    G_CALLBACK (on_radiobutton_diner3_fn_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton_dejeuner3_fn, "toggled",
                    G_CALLBACK (on_radiobutton_dejeuner3_fn_toggled),
                    NULL);
  g_signal_connect ((gpointer) button_home3_fn, "clicked",
                    G_CALLBACK (on_button_home3_fn_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_suppression_fn, "clicked",
                    G_CALLBACK (on_button_suppression_fn_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Supprimer_fn, Supprimer_fn, "Supprimer_fn");
  GLADE_HOOKUP_OBJECT (Supprimer_fn, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (Supprimer_fn, label_temps3_fn, "label_temps3_fn");
  GLADE_HOOKUP_OBJECT (Supprimer_fn, label_jour3_fn, "label_jour3_fn");
  GLADE_HOOKUP_OBJECT (Supprimer_fn, label_suppresssion_fn, "label_suppresssion_fn");
  GLADE_HOOKUP_OBJECT (Supprimer_fn, combobox_suppression_fn, "combobox_suppression_fn");
  GLADE_HOOKUP_OBJECT (Supprimer_fn, radiobutton_diner3_fn, "radiobutton_diner3_fn");
  GLADE_HOOKUP_OBJECT (Supprimer_fn, radiobutton_dejeuner3_fn, "radiobutton_dejeuner3_fn");
  GLADE_HOOKUP_OBJECT (Supprimer_fn, button_home3_fn, "button_home3_fn");
  GLADE_HOOKUP_OBJECT (Supprimer_fn, image17, "image17");
  GLADE_HOOKUP_OBJECT (Supprimer_fn, button_suppression_fn, "button_suppression_fn");
  GLADE_HOOKUP_OBJECT (Supprimer_fn, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (Supprimer_fn, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (Supprimer_fn, image15, "image15");
  GLADE_HOOKUP_OBJECT (Supprimer_fn, label19, "label19");

  return Supprimer_fn;
}

GtkWidget*
create_authentification_fn (void)
{
  GtkWidget *authentification_fn;
  GtkWidget *fixed6;
  GtkWidget *entry_login_fn;
  GtkWidget *entry_id_fn;
  GtkWidget *label39;
  GtkWidget *label_login_fn;
  GtkWidget *label_id_fn;
  GtkWidget *button_connection_fn;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image18;
  GtkWidget *label22;

  authentification_fn = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (authentification_fn, 555, 400);
  gtk_window_set_title (GTK_WINDOW (authentification_fn), _("authentification"));

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (authentification_fn), fixed6);

  entry_login_fn = gtk_entry_new ();
  gtk_widget_show (entry_login_fn);
  gtk_fixed_put (GTK_FIXED (fixed6), entry_login_fn, 264, 120);
  gtk_widget_set_size_request (entry_login_fn, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_login_fn), 8226);

  entry_id_fn = gtk_entry_new ();
  gtk_widget_show (entry_id_fn);
  gtk_fixed_put (GTK_FIXED (fixed6), entry_id_fn, 264, 176);
  gtk_widget_set_size_request (entry_id_fn, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_id_fn), 8226);

  label39 = gtk_label_new (_("------- Authentification -------"));
  gtk_widget_show (label39);
  gtk_fixed_put (GTK_FIXED (fixed6), label39, 176, 32);
  gtk_widget_set_size_request (label39, 192, 32);

  label_login_fn = gtk_label_new (_("Login  :"));
  gtk_widget_show (label_login_fn);
  gtk_fixed_put (GTK_FIXED (fixed6), label_login_fn, 72, 112);
  gtk_widget_set_size_request (label_login_fn, 112, 32);

  label_id_fn = gtk_label_new (_("Votre Identifiant  :"));
  gtk_widget_show (label_id_fn);
  gtk_fixed_put (GTK_FIXED (fixed6), label_id_fn, 64, 176);
  gtk_widget_set_size_request (label_id_fn, 136, 32);

  button_connection_fn = gtk_button_new ();
  gtk_widget_show (button_connection_fn);
  gtk_fixed_put (GTK_FIXED (fixed6), button_connection_fn, 200, 288);
  gtk_widget_set_size_request (button_connection_fn, 128, 40);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (button_connection_fn), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image18 = gtk_image_new_from_stock ("gtk-yes", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image18);
  gtk_box_pack_start (GTK_BOX (hbox10), image18, FALSE, FALSE, 0);

  label22 = gtk_label_new_with_mnemonic (_(" Connection"));
  gtk_widget_show (label22);
  gtk_box_pack_start (GTK_BOX (hbox10), label22, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button_connection_fn, "clicked",
                    G_CALLBACK (on_button_connection_fn_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (authentification_fn, authentification_fn, "authentification_fn");
  GLADE_HOOKUP_OBJECT (authentification_fn, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (authentification_fn, entry_login_fn, "entry_login_fn");
  GLADE_HOOKUP_OBJECT (authentification_fn, entry_id_fn, "entry_id_fn");
  GLADE_HOOKUP_OBJECT (authentification_fn, label39, "label39");
  GLADE_HOOKUP_OBJECT (authentification_fn, label_login_fn, "label_login_fn");
  GLADE_HOOKUP_OBJECT (authentification_fn, label_id_fn, "label_id_fn");
  GLADE_HOOKUP_OBJECT (authentification_fn, button_connection_fn, "button_connection_fn");
  GLADE_HOOKUP_OBJECT (authentification_fn, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (authentification_fn, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (authentification_fn, image18, "image18");
  GLADE_HOOKUP_OBJECT (authentification_fn, label22, "label22");

  return authentification_fn;
}

GtkWidget*
create_Modifier_fn (void)
{
  GtkWidget *Modifier_fn;
  GtkWidget *fixed9;
  GtkWidget *label9modifier_fn;
  GtkWidget *label_temps_modification;
  GtkWidget *table2;
  GtkWidget *label_jour_modification;
  GtkWidget *label_entree_modification;
  GtkWidget *label_plat_principal;
  GtkWidget *label_dessert;
  GtkWidget *entry_modification_fn;
  GtkWidget *entry_plat_modification_fn;
  GtkWidget *entry_dessert_modification_fn;
  GtkWidget *label_dechets;
  GtkObject *spinbutton_dechets_modification_fn_adj;
  GtkWidget *spinbutton_dechets_modification_fn;
  GtkWidget *combobox_jour_modification_fn;
  GtkWidget *button_sauvegarder_fn;
  GtkWidget *alignment16;
  GtkWidget *hbox16;
  GtkWidget *image26;
  GtkWidget *label42;
  GtkWidget *checkbutton_diner_modification_fn;
  GtkWidget *checkbutton_dejeuner_modification_fn;
  GtkWidget *button_home2_fn;
  GtkWidget *image27;

  Modifier_fn = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (Modifier_fn, 600, 648);
  gtk_window_set_title (GTK_WINDOW (Modifier_fn), _("Modifier"));

  fixed9 = gtk_fixed_new ();
  gtk_widget_show (fixed9);
  gtk_container_add (GTK_CONTAINER (Modifier_fn), fixed9);

  label9modifier_fn = gtk_label_new (_("------ Espace Nutritionniste ------\n          ------ Modification ------"));
  gtk_widget_show (label9modifier_fn);
  gtk_fixed_put (GTK_FIXED (fixed9), label9modifier_fn, 184, 8);
  gtk_widget_set_size_request (label9modifier_fn, 240, 64);

  label_temps_modification = gtk_label_new (_("Temps  :"));
  gtk_widget_show (label_temps_modification);
  gtk_fixed_put (GTK_FIXED (fixed9), label_temps_modification, 120, 120);
  gtk_widget_set_size_request (label_temps_modification, 72, 32);

  table2 = gtk_table_new (5, 2, FALSE);
  gtk_widget_show (table2);
  gtk_fixed_put (GTK_FIXED (fixed9), table2, 80, 208);
  gtk_widget_set_size_request (table2, 426, 320);
  gtk_table_set_row_spacings (GTK_TABLE (table2), 18);
  gtk_table_set_col_spacings (GTK_TABLE (table2), 8);

  label_jour_modification = gtk_label_new (_("Jour De La Semaine :"));
  gtk_widget_show (label_jour_modification);
  gtk_table_attach (GTK_TABLE (table2), label_jour_modification, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (label_jour_modification, 184, 40);

  label_entree_modification = gtk_label_new (_("Entree"));
  gtk_widget_show (label_entree_modification);
  gtk_table_attach (GTK_TABLE (table2), label_entree_modification, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (label_entree_modification, 184, 40);

  label_plat_principal = gtk_label_new (_("Plat principal"));
  gtk_widget_show (label_plat_principal);
  gtk_table_attach (GTK_TABLE (table2), label_plat_principal, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (label_plat_principal, 184, 40);

  label_dessert = gtk_label_new (_("Dessert"));
  gtk_widget_show (label_dessert);
  gtk_table_attach (GTK_TABLE (table2), label_dessert, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (label_dessert, 184, 40);

  entry_modification_fn = gtk_entry_new ();
  gtk_widget_show (entry_modification_fn);
  gtk_table_attach (GTK_TABLE (table2), entry_modification_fn, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_modification_fn), 8226);

  entry_plat_modification_fn = gtk_entry_new ();
  gtk_widget_show (entry_plat_modification_fn);
  gtk_table_attach (GTK_TABLE (table2), entry_plat_modification_fn, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_plat_modification_fn), 8226);

  entry_dessert_modification_fn = gtk_entry_new ();
  gtk_widget_show (entry_dessert_modification_fn);
  gtk_table_attach (GTK_TABLE (table2), entry_dessert_modification_fn, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_dessert_modification_fn), 8226);

  label_dechets = gtk_label_new (_("D\303\251chets en kg :"));
  gtk_widget_show (label_dechets);
  gtk_table_attach (GTK_TABLE (table2), label_dechets, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (label_dechets, 144, 40);

  spinbutton_dechets_modification_fn_adj = gtk_adjustment_new (0, 0, 100, 1, 10, 10);
  spinbutton_dechets_modification_fn = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_dechets_modification_fn_adj), 1, 0);
  gtk_widget_show (spinbutton_dechets_modification_fn);
  gtk_table_attach (GTK_TABLE (table2), spinbutton_dechets_modification_fn, 1, 2, 4, 5,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (spinbutton_dechets_modification_fn, 60, 27);

  combobox_jour_modification_fn = gtk_combo_box_new_text ();
  gtk_widget_show (combobox_jour_modification_fn);
  gtk_table_attach (GTK_TABLE (table2), combobox_jour_modification_fn, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_jour_modification_fn), _("lundi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_jour_modification_fn), _("mardi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_jour_modification_fn), _("mercredi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_jour_modification_fn), _("jeudi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_jour_modification_fn), _("vendredi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_jour_modification_fn), _("samedi"));

  button_sauvegarder_fn = gtk_button_new ();
  gtk_widget_show (button_sauvegarder_fn);
  gtk_fixed_put (GTK_FIXED (fixed9), button_sauvegarder_fn, 224, 552);
  gtk_widget_set_size_request (button_sauvegarder_fn, 136, 48);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (button_sauvegarder_fn), alignment16);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox16);

  image26 = gtk_image_new_from_stock ("gtk-floppy", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image26);
  gtk_box_pack_start (GTK_BOX (hbox16), image26, FALSE, FALSE, 0);

  label42 = gtk_label_new_with_mnemonic (_(" Sauvegarder"));
  gtk_widget_show (label42);
  gtk_box_pack_start (GTK_BOX (hbox16), label42, FALSE, FALSE, 0);

  checkbutton_diner_modification_fn = gtk_check_button_new_with_mnemonic (_("Diner"));
  gtk_widget_show (checkbutton_diner_modification_fn);
  gtk_fixed_put (GTK_FIXED (fixed9), checkbutton_diner_modification_fn, 272, 144);
  gtk_widget_set_size_request (checkbutton_diner_modification_fn, 118, 32);

  checkbutton_dejeuner_modification_fn = gtk_check_button_new_with_mnemonic (_("D\303\251jeuner"));
  gtk_widget_show (checkbutton_dejeuner_modification_fn);
  gtk_fixed_put (GTK_FIXED (fixed9), checkbutton_dejeuner_modification_fn, 272, 112);
  gtk_widget_set_size_request (checkbutton_dejeuner_modification_fn, 120, 32);

  button_home2_fn = gtk_button_new ();
  gtk_widget_show (button_home2_fn);
  gtk_fixed_put (GTK_FIXED (fixed9), button_home2_fn, 32, 24);
  gtk_widget_set_size_request (button_home2_fn, 48, 32);

  image27 = gtk_image_new_from_stock ("gtk-home", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image27);
  gtk_container_add (GTK_CONTAINER (button_home2_fn), image27);

  g_signal_connect ((gpointer) button_sauvegarder_fn, "clicked",
                    G_CALLBACK (on_button_sauvegarder_fn_clicked),
                    NULL);
  g_signal_connect ((gpointer) checkbutton_diner_modification_fn, "toggled",
                    G_CALLBACK (on_checkbutton_diner_modification_fn_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton_dejeuner_modification_fn, "toggled",
                    G_CALLBACK (on_checkbutton_dejeuner_modification_fn_toggled),
                    NULL);
  g_signal_connect ((gpointer) button_home2_fn, "clicked",
                    G_CALLBACK (on_button_home2_fn_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Modifier_fn, Modifier_fn, "Modifier_fn");
  GLADE_HOOKUP_OBJECT (Modifier_fn, fixed9, "fixed9");
  GLADE_HOOKUP_OBJECT (Modifier_fn, label9modifier_fn, "label9modifier_fn");
  GLADE_HOOKUP_OBJECT (Modifier_fn, label_temps_modification, "label_temps_modification");
  GLADE_HOOKUP_OBJECT (Modifier_fn, table2, "table2");
  GLADE_HOOKUP_OBJECT (Modifier_fn, label_jour_modification, "label_jour_modification");
  GLADE_HOOKUP_OBJECT (Modifier_fn, label_entree_modification, "label_entree_modification");
  GLADE_HOOKUP_OBJECT (Modifier_fn, label_plat_principal, "label_plat_principal");
  GLADE_HOOKUP_OBJECT (Modifier_fn, label_dessert, "label_dessert");
  GLADE_HOOKUP_OBJECT (Modifier_fn, entry_modification_fn, "entry_modification_fn");
  GLADE_HOOKUP_OBJECT (Modifier_fn, entry_plat_modification_fn, "entry_plat_modification_fn");
  GLADE_HOOKUP_OBJECT (Modifier_fn, entry_dessert_modification_fn, "entry_dessert_modification_fn");
  GLADE_HOOKUP_OBJECT (Modifier_fn, label_dechets, "label_dechets");
  GLADE_HOOKUP_OBJECT (Modifier_fn, spinbutton_dechets_modification_fn, "spinbutton_dechets_modification_fn");
  GLADE_HOOKUP_OBJECT (Modifier_fn, combobox_jour_modification_fn, "combobox_jour_modification_fn");
  GLADE_HOOKUP_OBJECT (Modifier_fn, button_sauvegarder_fn, "button_sauvegarder_fn");
  GLADE_HOOKUP_OBJECT (Modifier_fn, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (Modifier_fn, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (Modifier_fn, image26, "image26");
  GLADE_HOOKUP_OBJECT (Modifier_fn, label42, "label42");
  GLADE_HOOKUP_OBJECT (Modifier_fn, checkbutton_diner_modification_fn, "checkbutton_diner_modification_fn");
  GLADE_HOOKUP_OBJECT (Modifier_fn, checkbutton_dejeuner_modification_fn, "checkbutton_dejeuner_modification_fn");
  GLADE_HOOKUP_OBJECT (Modifier_fn, button_home2_fn, "button_home2_fn");
  GLADE_HOOKUP_OBJECT (Modifier_fn, image27, "image27");

  return Modifier_fn;
}

