/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_Gestionf_fn (void);
GtkWidget* create_Rechercher_fn (void);
GtkWidget* create_Ajout_fn (void);
GtkWidget* create_Supprimer_fn (void);
GtkWidget* create_authentification_fn (void);
GtkWidget* create_Modifier_fn (void);
