/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *Gestionf_fn;
  GtkWidget *Rechercher_fn;
  GtkWidget *Ajout_fn;
  GtkWidget *Supprimer_fn;
  GtkWidget *authentification_fn;
  GtkWidget *Modifier_fn;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  //Gestionf_fn = create_Gestionf_fn ();
  //gtk_widget_show (Gestionf_fn);
  //Rechercher_fn = create_Rechercher_fn ();
  //gtk_widget_show (Rechercher_fn);
  //Ajout_fn = create_Ajout_fn ();
  //gtk_widget_show (Ajout_fn);
  //Supprimer_fn = create_Supprimer_fn ();
  //gtk_widget_show (Supprimer_fn);
  authentification_fn = create_authentification_fn ();
  gtk_widget_show (authentification_fn);
  //Modifier_fn = create_Modifier_fn ();
  //gtk_widget_show (Modifier_fn);

  gtk_main ();
  return 0;
}

